default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: ^(requirements/\w*.in)$
        args: ["--ignore-case", "--unique"]
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.267
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.13.0"
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.2"]
  - repo: https://github.com/psf/black
    rev: "23.3.0"
    hooks:
      - id: black
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "0.11.2"
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.9-for-vscode"
    hooks:
      - id: prettier
        exclude_types: [html]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.3.0"
    hooks:
      - id: mypy
  - repo: https://github.com/pycqa/bandit
    rev: "1.7.5"
    hooks:
      - id: bandit
        additional_dependencies: ["bandit[toml]"]
        args: ["--configfile", "pyproject.toml", "--quiet", "--recursive"]
  - repo: https://github.com/trailofbits/pip-audit
    rev: v2.5.5
    hooks:
      - id: pip-audit
        additional_dependencies:
          - requests~=2.29.0
        args: ["--require-hashes", "--requirement", "requirements/common.txt"]
