[tool.black]
target-version = ["py310"]

[tool.coverage.html]
title = "Django Queries - Coverage"

[tool.coverage.report]
fail_under = 100
show_missing = true

[tool.coverage.run]
branch = true
concurrency = ["multiprocessing"]
data_file = ".coverages/.coverage"
disable_warnings = ["no-data-collected"]
omit = [
    ".venv/*",
    "djangoqueries/asgi.py",
    "djangoqueries/workers.py",
    "djangoqueries/wsgi.py",
    "manage*.py",
    "venv/*",
]
source = ["."]

[tool.isort]
atomic = true
combine_as_imports = true
default_section = "THIRDPARTY"
known_first_party = [
    "blog",
    "djangoqueries",
    "shows"
]
known_third_party = "django"
profile = "black"
skip = [
    ".vscode-server",
]

[tool.mypy]
ignore_missing_imports = true
python_version = "3.10"
