[tool.ruff]
target-version = "py312"

format.docstring-code-format = true
lint.select = [
  "A",   # flake8-builtins
  "B",   # flake8-bugbear
  "C4",  # flake8-comprehensions
  "C90", # McCabe cyclomatic complexity
  "D",   # pydocstyle
  "DJ",  # flake8-django
  "E",   # pycodestyle errors
  "F",   # Pyflakes
  "I",   # isort
  "Q",   # flake8-quotes
  "UP",  # pyupgrade
  "W",   # pycodestyle warnings
]
lint.ignore = [
  "D203",
  "D212",
]
lint.per-file-ignores."*/migrations/*.py" = [
  "D100",
  "D101",
  "D102",
  "D104",
]
lint.per-file-ignores."djangoqueries/*sgi.py" = [
  "E402",
]
lint.isort.known-first-party = [
  "blog",
  "djangoqueries",
  "shows",
]
lint.isort.known-third-party = [
  "django",
]

[tool.coverage.html]
title = "Django Queries - Coverage"

[tool.coverage.report]
fail_under = 100
show_missing = true

[tool.coverage.run]
branch = true
concurrency = [ "multiprocessing" ]
data_file = ".coverages/.coverage"
disable_warnings = [ "no-data-collected" ]
omit = [
  ".venv/*",
  "djangoqueries/asgi.py",
  "djangoqueries/workers.py",
  "djangoqueries/wsgi.py",
  "manage*.py",
  "venv/*",
]
source = [ "." ]

[tool.bandit]
exclude_dirs = [ ".venv", "tests" ]
